/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Escolhendo_Signo.java
 *
 * Created on 28/06/2022, 14:24:57
 */
package aula_7;
import javax.swing.JOptionPane;
/**
 *
 * @author Aluno
 */
public class Escolhendo_Signo extends javax.swing.JFrame {

    /** Creates new form Escolhendo_Signo */
    public Escolhendo_Signo() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBGGrupoOpcoes = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRAries = new javax.swing.JRadioButton();
        jRTouro = new javax.swing.JRadioButton();
        jRGemeos = new javax.swing.JRadioButton();
        jRCancer = new javax.swing.JRadioButton();
        jRLeao = new javax.swing.JRadioButton();
        jRVirgem = new javax.swing.JRadioButton();
        jRLibra = new javax.swing.JRadioButton();
        jREscorpiao = new javax.swing.JRadioButton();
        jRSagitario = new javax.swing.JRadioButton();
        jRCapricornio = new javax.swing.JRadioButton();
        jRAquario = new javax.swing.JRadioButton();
        jRPeixes = new javax.swing.JRadioButton();
        jBVeja = new javax.swing.JButton();
        jBSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Signos");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Signos - Escolha o seu:");

        jBGGrupoOpcoes.add(jRAries);
        jRAries.setText("Aries");

        jBGGrupoOpcoes.add(jRTouro);
        jRTouro.setText("Touro");

        jBGGrupoOpcoes.add(jRGemeos);
        jRGemeos.setText("Gêmeos");

        jBGGrupoOpcoes.add(jRCancer);
        jRCancer.setText("Câncer");

        jBGGrupoOpcoes.add(jRLeao);
        jRLeao.setText("Leão");

        jBGGrupoOpcoes.add(jRVirgem);
        jRVirgem.setText("Virgem");

        jBGGrupoOpcoes.add(jRLibra);
        jRLibra.setText("Libra");

        jBGGrupoOpcoes.add(jREscorpiao);
        jREscorpiao.setText("Escorpião");

        jBGGrupoOpcoes.add(jRSagitario);
        jRSagitario.setText("Sagitário");

        jBGGrupoOpcoes.add(jRCapricornio);
        jRCapricornio.setText("Capricórnio");

        jBGGrupoOpcoes.add(jRAquario);
        jRAquario.setText("Aquário");

        jBGGrupoOpcoes.add(jRPeixes);
        jRPeixes.setText("Peixes");

        jBVeja.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBVeja.setText("Veja o que diz seu signo:");
        jBVeja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVejaActionPerformed(evt);
            }
        });

        jBSair.setText("Sair");
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBVeja)
                        .addGap(39, 39, 39)
                        .addComponent(jBSair))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRAries)
                            .addComponent(jRTouro)
                            .addComponent(jRGemeos)
                            .addComponent(jRCancer)
                            .addComponent(jRLeao)
                            .addComponent(jRVirgem))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRPeixes)
                            .addComponent(jRAquario)
                            .addComponent(jRCapricornio)
                            .addComponent(jRSagitario)
                            .addComponent(jREscorpiao)
                            .addComponent(jRLibra))))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRAries)
                    .addComponent(jRLibra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRTouro)
                    .addComponent(jREscorpiao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRGemeos)
                    .addComponent(jRSagitario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRCancer)
                    .addComponent(jRCapricornio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRLeao)
                    .addComponent(jRAquario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRVirgem)
                    .addComponent(jRPeixes))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBVeja)
                    .addComponent(jBSair))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jBVejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVejaActionPerformed
// TODO add your handling code here:
    if(jRAries.isSelected()){
        JOptionPane.showMessageDialog(null, "O primeiro signo do zodíaco, está sempre a frente das situações.");
    }
    else if (jRTouro.isSelected()){
        JOptionPane.showMessageDialog(null, "Pode ser do elemento Terra, gosta de ter o controle das situações em suas mãos.");
    }
    else if (jRGemeos.isSelected()){
        JOptionPane.showMessageDialog(null, "É inteligente, dinâmica, vibrante, sempre em busca de novos desafios.");
    }
    else if (jRCancer.isSelected()){
        JOptionPane.showMessageDialog(null, "Tem uma grande intuição, que a guia nos momentos-chave do destino.");
    }
    else if (jRLeao.isSelected()){
        JOptionPane.showMessageDialog(null, "Tem muitos talentos, adora balada, música, cinema e ama animais de estimação.");
    }
    else if (jRVirgem.isSelected()){
        JOptionPane.showMessageDialog(null, "Tem muito talento para a escrita, e têm um jeitinho crítico, que pode ajudá-las na profissão.");
    }
    else if (jRLibra.isSelected()){
        JOptionPane.showMessageDialog(null, "Você, sabe o valor das outras pessoas, das boas amizades e dos relacionamentos afetivos.");
    }
    else if (jREscorpiao.isSelected()){
        JOptionPane.showMessageDialog(null, "Sua persistência e teimosia podem ultrapassar muitas barreiras.");
    }
    else if (jRSagitario.isSelected()){
        JOptionPane.showMessageDialog(null, "Seu jeito expansivo não passa despercebido.");
    }
    else if (jRCapricornio.isSelected()){
        JOptionPane.showMessageDialog(null, "Você não foge de uma boa discussão e adora uma balada.");
    }
    else if (jRAquario.isSelected()){
        JOptionPane.showMessageDialog(null, "Seu signo é chamado de futurista.");
    }
    else if (jRPeixes.isSelected()){
        JOptionPane.showMessageDialog(null, "Tem desejo de fazer algo grandioso pelo mundo.");
    }
}//GEN-LAST:event_jBVejaActionPerformed

private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
// TODO add your handling code here:
    System.exit(0);
}//GEN-LAST:event_jBSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Escolhendo_Signo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Escolhendo_Signo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Escolhendo_Signo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Escolhendo_Signo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Escolhendo_Signo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup jBGGrupoOpcoes;
    private javax.swing.JButton jBSair;
    private javax.swing.JButton jBVeja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRAquario;
    private javax.swing.JRadioButton jRAries;
    private javax.swing.JRadioButton jRCancer;
    private javax.swing.JRadioButton jRCapricornio;
    private javax.swing.JRadioButton jREscorpiao;
    private javax.swing.JRadioButton jRGemeos;
    private javax.swing.JRadioButton jRLeao;
    private javax.swing.JRadioButton jRLibra;
    private javax.swing.JRadioButton jRPeixes;
    private javax.swing.JRadioButton jRSagitario;
    private javax.swing.JRadioButton jRTouro;
    private javax.swing.JRadioButton jRVirgem;
    // End of variables declaration//GEN-END:variables
}
