/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Maior_Menor.java
 *
 * Created on 06/07/2022, 14:52:40
 */
package exercicio_9;
import javax.swing.JOptionPane;
/**
 *
 * @author Aluno
 */
public class Maior_Menor extends javax.swing.JFrame {

    /** Creates new form Maior_Menor */
    public Maior_Menor() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botões = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRMaior = new javax.swing.JRadioButton();
        jRMenor = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTNum1 = new javax.swing.JTextField();
        jTNum2 = new javax.swing.JTextField();
        jTNum3 = new javax.swing.JTextField();
        jBCalcular = new javax.swing.JButton();
        jBLimpar = new javax.swing.JButton();
        jBSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Selecione a opção desejada!");

        botões.add(jRMaior);
        jRMaior.setText("Maior Número");
        jRMaior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRMaiorActionPerformed(evt);
            }
        });

        botões.add(jRMenor);
        jRMenor.setText("Menor Número");
        jRMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRMenorActionPerformed(evt);
            }
        });

        jLabel2.setText("1° Número :");

        jLabel3.setText("2° Número :");

        jLabel4.setText("3° Número :");

        jTNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNum2ActionPerformed(evt);
            }
        });

        jBCalcular.setText("Calcular");
        jBCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCalcularActionPerformed(evt);
            }
        });

        jBLimpar.setText("Limpar");
        jBLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimparActionPerformed(evt);
            }
        });

        jBSair.setText("Sair");
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRMaior)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRMenor))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTNum3))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTNum2))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBLimpar)
                    .addComponent(jBCalcular)
                    .addComponent(jBSair))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRMaior)
                    .addComponent(jRMenor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCalcular))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBLimpar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTNum3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBSair))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jTNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNum2ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTNum2ActionPerformed

private void jBCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCalcularActionPerformed
// TODO add your handling code here:
    double num1;
    double num2;
    double num3;
    num1 = Double.parseDouble(jTNum1.getText());
    num2 = Double.parseDouble(jTNum2.getText());
    num3 = Double.parseDouble(jTNum3.getText());
   if(jRMaior.isSelected()){
    if(num1 > num2 && num1 > num3){
        JOptionPane.showMessageDialog(null, num1 + " é o maior número. ");
    } 
    else if(num2 > num1 && num2 > num3){ 
        JOptionPane.showMessageDialog(null, num2 + " é o maior número. ");
    }
    else if(num3 > num1 && num3 > num2){ 
        JOptionPane.showMessageDialog(null, num3 + " é o maior número. ");
    }
   }
    else if(jRMenor.isSelected()){
      if(num1 < num2 && num1 < num3){
     JOptionPane.showMessageDialog(null, num1 + " é o menor número. ");
    }
      else if(num2 < num1 && num2 < num3 ){
          JOptionPane.showMessageDialog(null, num2 + " é o menor número. ");
      }
    else if(num3 < num1 && num3 < num2){ 
        JOptionPane.showMessageDialog(null, num3 + " é o menor número. ");
    }
    }
   else{
        JOptionPane.showMessageDialog(null,"Selecione a opção desejada.");
    }
}//GEN-LAST:event_jBCalcularActionPerformed

private void jRMaiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRMaiorActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jRMaiorActionPerformed

private void jBLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimparActionPerformed
// TODO add your handling code here:
    jTNum1.setText(null);
    jTNum2.setText(null);
    jTNum3.setText(null);   
    
}//GEN-LAST:event_jBLimparActionPerformed

private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
// TODO add your handling code here:
    System.exit(0);
}//GEN-LAST:event_jBSairActionPerformed

private void jRMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRMenorActionPerformed
// TODO add your handling code here:

}//GEN-LAST:event_jRMenorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Maior_Menor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Maior_Menor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Maior_Menor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Maior_Menor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Maior_Menor().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup botões;
    private javax.swing.JButton jBCalcular;
    private javax.swing.JButton jBLimpar;
    private javax.swing.JButton jBSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRMaior;
    private javax.swing.JRadioButton jRMenor;
    private javax.swing.JTextField jTNum1;
    private javax.swing.JTextField jTNum2;
    private javax.swing.JTextField jTNum3;
    // End of variables declaration//GEN-END:variables
}
