/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SignoSwitch.java
 *
 * Created on 29/06/2022, 08:44:16
 */
package aula_8;
import javax.swing.JOptionPane;
/**
 *
 * @author Aluno
 */
public class SignoSwitch extends javax.swing.JFrame {

    /** Creates new form SignoSwitch */
    public SignoSwitch() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCBSignos = new javax.swing.JComboBox();
        jBResposta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Signos");

        jLabel1.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel1.setText("Signos - Escolha o seu:");

        jCBSignos.setEditable(true);
        jCBSignos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Áries", "Touro", "Gêmeos", "Câncer", "Leão", "Virgem", "Libra", "Escorpião", "Sagitário", "Capricórnio", "Aquário", "Peixes" }));

        jBResposta.setText("Veja o que diz o seu signo:");
        jBResposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRespostaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCBSignos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBResposta))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jCBSignos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBResposta)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jBRespostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRespostaActionPerformed
// TODO add your handling code here:
    switch (jCBSignos.getSelectedIndex()){
        case 0 :
            JOptionPane.showMessageDialog(null, "O primeiro signo do zodíaco é também pioneiro em tudo, está sempre tomando a frente das situações."); break;
        case 1:  
            JOptionPane.showMessageDialog(null, "Por ser do elemento terra, gosta de ter o controle das situações em suas mãos."); break;
        case 2:
            JOptionPane.showMessageDialog(null, "É inteligente, dinâmica, vibrante, sempre em busca de novos desafios."); break;
        case 3:
            JOptionPane.showMessageDialog(null, "Tem uma super intuição, que a guia nos momentos-chave do destino."); break;
        case 4:
            JOptionPane.showMessageDialog(null, "Tem muitos talentos, adora balada, cinema, música e ama animais de estimação."); break;
        case 5:
            JOptionPane.showMessageDialog(null, "Têm muito talento para a escrita, e têm um jeitinho crítico, que pode ajudá-las na profissão."); break;
        case 6:
            JOptionPane.showMessageDialog(null, "Você, mais que ninguém, sabe o valor das outras pessoas, das boas amizades, dos relacionamentos afetivos."); break;
        case 7:
            JOptionPane.showMessageDialog(null, "Sua persistência e teimosia podem ultrapassar muitas barreiras."); break;
        case 8:
            JOptionPane.showMessageDialog(null, "Seu jeito expansivo não passa despercebido."); break;
        case 9:
            JOptionPane.showMessageDialog(null, "Você não foge de uma boa discussão e adora uma balada."); break;
        case 10:
            JOptionPane.showMessageDialog(null, "Seu signo é chamado de futurista."); break;
        case 11 :
            JOptionPane.showMessageDialog(null, "Tem desejo de fazer algo grandioso pelo mundo."); break;
        default:
            JOptionPane.showMessageDialog(null, "Esse não é um signo válido."); break;
    }
}//GEN-LAST:event_jBRespostaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignoSwitch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignoSwitch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignoSwitch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignoSwitch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SignoSwitch().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBResposta;
    private javax.swing.JComboBox jCBSignos;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
